### ISSUE TITLE
Provide callbacks for the native methods

### ISSUE THREAD

**Issue by antonio-ivanovski** [toteto/react-native-background-job#1]
There should be a callback to RN depending on the success of the following methods: **schedule**, **cancel** and **cancelAll**

**Comment by antonio-ivanovski** [comment]
@bevkoski a quick look on https://github.com/toteto/react-native-background-job/commit/b4264a95b7943ed90af35911e2f4747d944f5be6 ?

**Comment by bevkoski** [comment]
@toteto, I looked at it, and besides some small small typos that need to be fixed and restructuring that needs to be done, everything looks fine.
